# Redirect with a 301
[[redirects]]
from = "/opportunities"
to = "/opportunities/faculty-research-grants"
status = 301

# Redirect not found pages to homepage
[[redirects]]
from = "/*"
to = "/"
status = 404